FROM opensuse/tumbleweed:latest

#ARG TUMBLEWEED_REPO_OSS=http://download.opensuse.org/tumbleweed/repo/oss/
#RUN /usr/bin/sed -ibak -e "s#baseurl.*#baseurl=$TUMBLEWEED_REPO_OSS#" /etc/zypp/repos.d/repo-oss.repo

RUN /usr/bin/zypper refresh
RUN /usr/bin/zypper --non-interactive update
RUN /usr/bin/zypper --non-interactive install pam-devel \
    libopenssl-devel \
    libudev-devel \
    sqlite3-devel \
    curl \
    git \
    gcc \
    sccache \
    which \
    unzip \
    iproute2 \
    rust cargo
RUN /usr/bin/zypper clean -a

# install awscli
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
WORKDIR /tmp/
RUN unzip awscliv2.zip
RUN ./aws/install
RUN rm -rf /tmp/aws*

COPY RUST_VERSION /etc/RUST_VERSION
COPY identify_os.sh /etc/profile.d/identify_os.sh

# because paths are hard
RUN echo 'PATH=$HOME/.cargo/bin:$PATH' >> /etc/profile


COPY build_* /usr/local/sbin/
RUN chmod 755 /usr/local/sbin/build_*.sh

# TODO: run this as non-root, because we don't need to
# USER 9000

CMD ["/usr/local/sbin/build_local_arch.sh" ]
