# syntax = edrevo/dockerfile-plus
# allow using include+

FROM opensuse/tumbleweed

ARG TUMBLEWEED_REPO_OSS=http://download.opensuse.org/tumbleweed/repo/oss/
RUN /usr/bin/sed -ibak -e "s#baseurl.*#baseurl=$TUMBLEWEED_REPO_OSS#" /etc/zypp/repos.d/repo-oss.repo

RUN zypper refresh
RUN zypper update
RUN zypper --non-interactive install libudev-devel sqlite3-devel libopenssl-devel curl git gcc sccache which pam-devel iproute2 aws-cli
RUN zypper clean -a

INCLUDE+ Dockerfile-common

