FROM opensuse/leap:15.2

RUN zypper -vv ref
RUN zypper --non-interactive install \
    libudev-devel \
    sqlite3-devel \
    libopenssl-devel pam-devel \
    timezone \
    sqlite3-devel sqlite3 \
    make automake autoconf \
    curl git gcc sccache which \
    iproute2  aws-cli
RUN zypper clean -a
RUN ln -s -f /usr/bin/clang /usr/bin/cc && \
	ln -s -f /usr/bin/ld.lld /usr/bin/ld

COPY install-rust.sh /usr/local/bin/
COPY RUST_VERSION /etc/RUST_VERSION

RUN chmod 755 /usr/local/bin/install-rust.sh
# because paths are hard
RUN echo 'PATH=$HOME/.cargo/bin:$PATH' >> /etc/profile

# because we don't need to run as root, it'd be nice to do this... but rustup gets in the way
# USER 9000

RUN /usr/local/bin/install-rust.sh

COPY build_local_arch.sh /usr/local/sbin/
RUN chmod 755 /usr/local/sbin/build_local_arch.sh

ENTRYPOINT ["/usr/local/sbin/build_local_arch.sh" ]
