FROM ubuntu:bionic

RUN apt-get update
RUN apt-get install -y git curl build-essential
RUN apt-get install -y libstd-rust-dev libssl-dev libsqlite3-dev clang libudev-dev libpam0g-dev
RUN apt-get install -y python3-pkgconfig

COPY RUST_VERSION /etc/RUST_VERSION

COPY install-rust.sh /usr/local/bin/
RUN chmod 755 /usr/local/bin/install-rust.sh

# because paths are hard
RUN echo 'PATH=$HOME/.cargo/bin:$PATH' >> /etc/profile

RUN /usr/local/bin/install-rust.sh

COPY build_local_arch.sh /usr/local/sbin/
RUN chmod 755 /usr/local/sbin/build_local_arch.sh

ENTRYPOINT ["/usr/local/sbin/build_local_arch.sh" ]