FROM opensuse/tumbleweed

ARG TUMBLEWEED_REPO_OSS=http://download.opensuse.org/tumbleweed/repo/oss/
RUN /usr/bin/sed -ibak -e "s#baseurl.*#baseurl=$TUMBLEWEED_REPO_OSS#" /etc/zypp/repos.d/repo-oss.repo

RUN /usr/bin/zypper refresh
RUN /usr/bin/zypper --non-interactive update
RUN /usr/bin/zypper --non-interactive install libudev-devel
RUN /usr/bin/zypper --non-interactive install libopenssl-devel
RUN /usr/bin/zypper --non-interactive install pam-devel
RUN /usr/bin/zypper --non-interactive install sqlite3-devel
RUN /usr/bin/zypper --non-interactive install curl
RUN /usr/bin/zypper --non-interactive install git
RUN /usr/bin/zypper --non-interactive install gcc
RUN /usr/bin/zypper --non-interactive install sccache
RUN /usr/bin/zypper --non-interactive install which
RUN /usr/bin/zypper --non-interactive install iproute2
RUN /usr/bin/zypper --non-interactive install aws-cli
RUN /usr/bin/zypper clean -a

COPY install-rust.sh /usr/local/bin/
COPY RUST_VERSION /etc/RUST_VERSION
COPY identify_os.sh /etc/profile.d/identify_os.sh


RUN chmod 755 /usr/local/bin/install-rust.sh
# because paths are hard
RUN echo 'PATH=$HOME/.cargo/bin:$PATH' >> /etc/profile

# because we don't need to run as root, it'd be nice to do this... but rustup gets in the way
# USER 9000

RUN /usr/local/bin/install-rust.sh

COPY build_local_arch.sh /usr/local/sbin/
RUN chmod 755 /usr/local/sbin/build_local_arch.sh

ENTRYPOINT ["/usr/local/sbin/build_local_arch.sh" ]
