
COPY RUST_VERSION /etc/RUST_VERSION
COPY install-rust.sh /usr/local/bin/
RUN chmod 755 /usr/local/bin/install-rust.sh
# because paths are hard
RUN echo 'PATH=$HOME/.cargo/bin:$PATH' >> /etc/profile


# because we don't need to run as root, it'd be nice to do this... but rustup gets in the way
# USER 9000

RUN /usr/local/bin/install-rust.sh

COPY build_local_arch.sh /usr/local/sbin/

ENTRYPOINT ["/usr/local/sbin/build_local_arch.sh" ]
