# syntax = edrevo/dockerfile-plus
# allow using include+

FROM ubuntu:bionic

RUN apt-get update
RUN apt-get install -y git curl build-essential libstd-rust-dev libssl-dev libsqlite3-dev clang libudev-dev libpam0g-dev

# TODO: get sccache working

INCLUDE+ Dockerfile-common
