FROM debian:buster
RUN apt-get update
RUN apt-get install -y git curl build-essential sccache



#RUN zypper update
#RUN zypper install libudev-devel sqlite3-devel libopenssl-devel npm-default



WORKDIR /tmp/
COPY install-rust.sh ./
RUN chmod +x install-rust.sh
RUN ./install-rust.sh
RUN rm install-rust.sh

RUN apt-get -y install librust-openssl-dev libssl-dev libsqlite3-dev clang

COPY build_local_arch.sh /usr/local/sbin/

CMD ["/usr/local/sbin/build_local_arch.sh" ]
