version: "3.9"

services:
  opensuse_leap_152:
    build:
        context: ./
        dockerfile: Dockerfile-opensuseleap152
        args:
          - HTTP_PROXY=${HTTP_PROXY}
    platform: linux/amd64
    env_file: .env

    volumes:
      - ./output:/output/
    # command: ["/usr/local/sbin/build_local_arch.sh"]

#   ubuntu_bionic:
#     image: ubuntu:bionic
#     platform: linux/amd64
#     env_file: .env
#     volumes:
  #       - ./build_local_arch.sh:/usr/local/sbin/build_local_arch.sh
  #       - ./output
  #   command: ["/usr/local/sbin/build_local_arch.sh"]

  #   ubuntu_focal:
    #     image: ubuntu:focal
    #     platform: linux/amd64
  #     env_file: .env
    #     volumes:
#       - ./build_local_arch.sh:/usr/local/sbin/build_local_arch.sh
#       - ./output
#     command: ["/usr/local/sbin/build_local_arch.sh"]


  debian_buster:
    build:
      context: ./
      dockerfile: Dockerfile-debianbuster
      args:
        - HTTP_PROXY=${HTTP_PROXY}
    platform: linux/amd64
    env_file: .env
    volumes:
      - ./output:/output/