# syntax = edrevo/dockerfile-plus
# allow using include+

FROM opensuse/leap:15.2

RUN zypper update
RUN zypper --non-interactive install libudev-devel sqlite3-devel libopenssl-devel curl git gcc sccache which

INCLUDE+ Dockerfile-common

