version: "3.9"

services:
  opensuse_leap_152:
    build:
        context: ./
        dockerfile: Dockerfile-opensuseleap152
        args:
          - HTTP_PROXY=${HTTP_PROXY}
          - SOURCE_REPO=${SOURCE_REPO}
          - SOURCE_REPO_BRANCH=${SOURCE_REPO_BRANCH}
    # platform: linux/amd64
    env_file: .env

    volumes:
      - ./output:/output/
      - opensuse_leap_152:/source

  opensuse_tumbleweed:
    build:
        context: ./
        dockerfile: Dockerfile-opensuse-tumbleweed
        args:
          - HTTP_PROXY=${HTTP_PROXY}
          - SOURCE_REPO=${SOURCE_REPO}
          - SOURCE_REPO_BRANCH=${SOURCE_REPO_BRANCH}
    # platform: linux/amd64
    env_file: .env

    volumes:
      - ./output:/output/
      - opensuse_tumbleweed:/source

  build_ubuntu_bionic:
    image: ubuntu:bionic
    # platform: linux/amd64
    build:
      context: ./
      dockerfile: Dockerfile-ubuntu-bionic
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - SOURCE_REPO=${SOURCE_REPO}
        - SOURCE_REPO_BRANCH=${SOURCE_REPO_BRANCH}
    env_file: .env

    volumes:
      - ./output:/output/
      - ubuntu_bionic:/source
    command: ["/usr/local/sbin/build_local_arch.sh"]

    # ubuntu_focal:
    #     image: ubuntu:focal


  debian_buster:
    build:
      context: ./
      dockerfile: Dockerfile-debianbuster
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - SOURCE_REPO=${SOURCE_REPO}
        - SOURCE_REPO_BRANCH=${SOURCE_REPO_BRANCH}
    # platform: linux/amd64
    env_file: .env
    volumes:
      - ./output:/output/
      - debian_buster:/source
  volumes:
    debian_buster:
    ubuntu_bionic:
    opensuse_tumbleweed:
    opensuse_leap_152:
